---
name: Feedback Form - Responsible AI Content
about: Suggest changes or improvements to the Responsible AI Content in this repository.
title: "[Feedback]: "
labels: ["feedback", "enhancement"]
assignees: []
---

fields:
  - name: Which document or section are you referring to?
    description: Provide the title or link to the specific document or section.
    example: "patient-discharge-summarization / README.md" or "[Link to the specific section]"

  - name: What would you like to see changed?
    description: Describe the specific content you believe should be updated, clarified, or improved.
    example: "Intended Use description for DocLens needs to be refined."

  - name: How do you suggest it be improved?
    description: Offer your recommendation for enhancing the content.
    example: "Language to improve the Intended Use description includes: [add language here]"

  - name: Why is this change important?
    description: Explain how this modification will benefit users or improve the repository.
    example: "Providing further contextualization will help users better understand and implement the DocLens method/metric."

  - name: Can you provide an example or reference? (Optional)
    description: If available, share a link, screenshot, or text that illustrates your suggestion.
    example: "See the DocLens description in [Another Resource] for a comprehensive explanation."

  - name: Additional comments or concerns?
    description: Any other feedback or questions?
    example: "Is there a plan to add more use cases in the future?"
